name: Build JSON Editor Executables

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            artifact_name: json_editor_windows.exe
            asset_name: json_editor-windows
          - os: macos-latest
            artifact_name: json_editor_mac
            asset_name: json_editor-mac
          - os: ubuntu-latest
            artifact_name: json_editor_linux
            asset_name: json_editor-linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4

    - name: Set up Python
      uses: actions/setup-python@v5  # Updated to v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Linux Dependencies (Ubuntu only)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y python3-tk

    - name: Build with PyInstaller
      run: |
        pyinstaller --noconsole --onefile --name ${{ matrix.artifact_name }} json_edit.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: ${{ matrix.asset_name }}
        path: dist/${{ matrix.artifact_name }}*
